manifest_version = 1
id = "ioptron-cem120-firmware"
name = "iOptron CEM120 Firmware"
description = "Firmware for iOptron CEM120 mount"
publisher = "iOptron"
homepage = "https://www.ioptron.com"
category = "driver"
type = "resource"
slug = "ioptron-cem120-firmware"

[install]
method = "exe"
elevation = true

[checkver]
provider = "html_scrape"
url = "https://www.ioptron.com/Articles.asp?ID=309"
regex = 'FW(\d{6})'

[checkver.autoupdate]
url = "https://www.ioptron.com/v/firmware/CEM120_FW230305.bin"
