manifest_version = 1
id = "losmandy-gemini-firmware"
name = "Losmandy Gemini 2 Firmware"
description = "Firmware for Losmandy Gemini 2 telescope mount controller"
publisher = "Losmandy"
homepage = "https://gemini-2.com"
category = "driver"
type = "resource"
slug = "losmandy-gemini-firmware"

[install]
method = "exe"
elevation = true

[checkver]
provider = "manual"

[checkver.autoupdate]
url = "https://gemini-2.com/firmware1/combined.zip"
