manifest_version = 1
id = "synscan-wifi-firmware"
name = "SynScan WiFi Adapter Firmware"
description = "Firmware for SynScan WiFi adapter"
publisher = "Sky-Watcher"
homepage = "https://www.skywatcher.com"
category = "driver"
type = "resource"
slug = "synscan-wifi-firmware"

[install]
method = "exe"
elevation = true

[checkver]
provider = "html_scrape"
url = "https://www.skywatcher.com/download/software/accessories/"
regex = 'Version (\d+\.\d+)'

[checkver.autoupdate]
url = "https://inter-static.skywatcher.com/downloads/synscan_wi-fi_adapter_firmware_version_$cleanVersion.zip"

[detection]
method = "ledger"
